server:
  port: 9001
spring:
  application:
    name: eureka-feign-consumer
  output:
    ansi:
      enabled: ALWAYS   #控制台彩色输出
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
feign:
  hystrix:
    enabled: true
    
#断路器的管理面板（springboot2.0.* 的配置项为）：
#actuator
management:
  server:
    port: 9101
  endpoints:
    web:
   #   base-path: / #修改访问路径  2.0之前默认是/   2.0默认是 /actuator  可以通过这个属性值修改
      exposure:
        include: '*'  #开放所有页面节点  默认只开启了health、info两个节点